import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#111827',
  muted: '#6B7280',
  faint: '#9CA3AF',
  line: '#E5E7EB',
  page: '#FFFFFF',
  surface: '#FFFFFF',
  soft: '#F7F4FB',
  softPurple: '#F4ECFF',
  purple: '#6D28D9',
  purpleDark: '#5B21B6',
  purpleLight: '#8B5CF6',
  green: '#22C55E',
  amber: '#F59E0B',
  red: '#EF4444',
  redSoft: '#FCE7E7',
};

const softShadow = {
  shadowColor: '#5B21B6',
  shadowOpacity: 0.18,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 8 },
  elevation: 6,
};

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.page,
  },
  chatBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.soft,
  },
  body: {
    flex: 1,
  },
  fullScreen: {
    flex: 1,
    backgroundColor: colors.page,
  },
  tabScreen: {
    flex: 1,
    backgroundColor: colors.page,
  },
  screenScroll: {
    flex: 1,
  },
  errorBanner: {
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: colors.red,
    backgroundColor: colors.redSoft,
    overflow: 'hidden',
  },

  header: {
    minHeight: 56,
    paddingHorizontal: 20,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandHeader: {
    minHeight: 56,
    paddingHorizontal: 20,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoMark: {
    position: 'absolute',
    left: 20,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 32,
    height: 32,
  },
  brand: {
    color: colors.purple,
    fontSize: 25,
    lineHeight: 30,
    fontWeight: '800',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
  },
  headerMeta: {
    alignItems: 'flex-end',
    gap: 6,
  },
  badge: {
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '700',
  },
  badgeOk: {
    color: colors.green,
    backgroundColor: '#EAFBF0',
  },
  badgeWarn: {
    color: colors.amber,
    backgroundColor: '#FFF7E6',
  },
  addressText: {
    color: colors.muted,
    fontSize: 12,
  },

  contextHeader: {
    minHeight: 56,
    paddingHorizontal: 16,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatHeader: {
    minHeight: 58,
    paddingHorizontal: 16,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    width: 18,
    height: 18,
    justifyContent: 'center',
  },
  backIconLineTop: {
    position: 'absolute',
    left: 1,
    top: 4,
    width: 14,
    height: 2,
    borderRadius: 2,
    backgroundColor: colors.ink,
    transform: [{ rotate: '-42deg' }],
  },
  backIconLineBottom: {
    position: 'absolute',
    left: 1,
    bottom: 4,
    width: 14,
    height: 2,
    borderRadius: 2,
    backgroundColor: colors.ink,
    transform: [{ rotate: '42deg' }],
  },
  contextTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatHeaderTitleBlock: {
    flex: 1,
    alignItems: 'center',
    gap: 1,
  },
  chatTitle: {
    maxWidth: '100%',
    color: colors.ink,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  chatStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  chatStatusTextLive: {
    color: colors.green,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  chatStatusTextSaved: {
    color: colors.faint,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  headerSpacer: {
    width: 44,
  },
  chatHeaderAction: {
    width: 44,
    minHeight: 44,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  chatHeaderActionText: {
    color: colors.purple,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
  },

  screenContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
    gap: 14,
  },
  formContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 32,
    gap: 24,
  },
  largeTitle: {
    color: colors.ink,
    fontSize: 34,
    lineHeight: 41,
    fontWeight: '700',
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 8,
  },
  sectionKicker: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginTop: 8,
    marginLeft: 6,
  },
  bodyCopy: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 22,
  },
  helperText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },

  searchBar: {
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: colors.soft,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    color: colors.ink,
    fontSize: 16,
    paddingVertical: 0,
  },
  searchIcon: {
    width: 20,
    height: 20,
  },

  groupedList: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  panel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 16,
    gap: 10,
  },
  formCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 16,
    gap: 12,
  },
  label: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  valueText: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
  },
  input: {
    minHeight: 52,
    borderRadius: 10,
    backgroundColor: colors.soft,
    color: colors.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
  },
  inputDisabled: {
    color: colors.faint,
    backgroundColor: colors.soft,
  },
  multiline: {
    minHeight: 86,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  agentRow: {
    minHeight: 81,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  historyRow: {
    minHeight: 76,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
  },
  swipeRow: {
    minHeight: 76,
    overflow: 'hidden',
    backgroundColor: colors.red,
  },
  swipeRowFront: {
    minHeight: 76,
    backgroundColor: colors.surface,
  },
  swipeDeleteAction: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 86,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.red,
  },
  swipeDeleteText: {
    color: colors.surface,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600',
  },
  settingsRowTall: {
    minHeight: 78,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsAgentRow: {
    minHeight: 72,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsConnectionRow: {
    minHeight: 72,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsActionRow: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  settingsActionText: {
    color: colors.purple,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '600',
  },
  settingsDangerText: {
    color: colors.red,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '600',
  },
  settingsMetricsRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsMetric: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  settingsMetricDivider: {
    width: 1,
    height: 34,
    backgroundColor: colors.line,
  },
  settingsMetricValue: {
    color: colors.ink,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '600',
  },
  settingsMetricLabel: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  listMain: {
    flex: 1,
    gap: 4,
  },
  historyMain: {
    flex: 1,
    gap: 4,
  },
  listTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '700',
  },
  listMeta: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  listSeparator: {
    height: 1,
    backgroundColor: colors.line,
  },
  listRowPressed: {
    backgroundColor: '#F0EDF4',
  },
  pressablePressed: {
    opacity: 0.62,
  },
  chevronImage: {
    width: 8,
    height: 12,
  },

  agentIconTile: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.softPurple,
  },
  agentGlyph: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agentGlyphCore: {
    width: 8,
    height: 8,
    borderRadius: 2,
    backgroundColor: colors.purple,
  },
  agentGlyphRing: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.purple,
  },
  statusWrap: {
    minWidth: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 5,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusDotLive: {
    backgroundColor: colors.green,
  },
  statusDotConnecting: {
    backgroundColor: colors.amber,
  },
  statusDotSaved: {
    backgroundColor: colors.faint,
  },
  statusText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  statusTextLive: {
    color: colors.green,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  statusTextConnecting: {
    color: colors.amber,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  statusTextSaved: {
    color: colors.faint,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },

  emptyState: {
    minHeight: 430,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 34,
    gap: 12,
  },
  emptyStateCompact: {
    minHeight: 240,
    justifyContent: 'flex-start',
    paddingTop: 28,
    paddingBottom: 20,
  },
  emptyIconTile: {
    width: 100,
    height: 100,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.soft,
    marginBottom: 18,
  },
  emptyIconTileCompact: {
    width: 72,
    height: 72,
    borderRadius: 16,
    marginBottom: 8,
  },
  emptyIconText: {
    color: colors.purple,
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '300',
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 25,
    lineHeight: 30,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyBody: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  welcomeScreen: {
    flex: 1,
    backgroundColor: colors.page,
    paddingHorizontal: 24,
    paddingBottom: 20,
  },
  welcomeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
  },
  welcomeLogoTile: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeLogoImage: {
    width: 96,
    height: 96,
  },
  welcomeTextBlock: {
    alignItems: 'center',
    gap: 8,
  },
  welcomeTitle: {
    color: colors.purple,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '700',
    textAlign: 'center',
  },
  welcomeBody: {
    maxWidth: 300,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  welcomeActions: {
    paddingBottom: 8,
  },

  fullWidthPrimaryButton: {
    minHeight: 52,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple,
  },
  fullWidthPrimaryButtonText: {
    color: colors.surface,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  fullWidthPrimaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButton: {
    minHeight: 42,
    borderRadius: 11,
    backgroundColor: colors.purple,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 42,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontWeight: '800',
  },
  dangerButton: {
    minHeight: 42,
    borderRadius: 11,
    backgroundColor: colors.red,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonText: {
    color: colors.surface,
    fontWeight: '800',
  },
  fab: {
    position: 'absolute',
    right: 25,
    bottom: 25,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple,
    ...softShadow,
  },
  fabPlus: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabPlusHorizontal: {
    position: 'absolute',
    width: 20,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.surface,
  },
  fabPlusVertical: {
    position: 'absolute',
    width: 3,
    height: 20,
    borderRadius: 2,
    backgroundColor: colors.surface,
  },

  codeCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: 16,
    marginBottom: 16,
  },
  codeText: {
    color: colors.ink,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },

  chatLayout: {
    flex: 1,
    backgroundColor: colors.page,
  },
  modeBar: {
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.page,
  },
  modeButton: {
    borderRadius: 8,
    backgroundColor: colors.soft,
    paddingHorizontal: 8,
    minHeight: 32,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeButtonActive: {
    backgroundColor: colors.softPurple,
  },
  modeText: {
    color: colors.muted,
    fontWeight: '600',
    fontSize: 13,
    lineHeight: 18,
  },
  modeTextActive: {
    color: colors.purple,
    fontWeight: '700',
  },
  modeCounter: {
    marginLeft: 'auto',
    color: colors.muted,
    fontSize: 10,
    fontWeight: '600',
  },
  messages: {
    flex: 1,
    backgroundColor: colors.soft,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 20,
    gap: 12,
  },
  userMessageWrap: {
    alignSelf: 'stretch',
    alignItems: 'flex-end',
    gap: 3,
  },
  agentMessageRow: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  agentMessageStack: {
    flex: 1,
    alignItems: 'flex-start',
    gap: 3,
  },
  chatAvatar: {
    width: 26,
    height: 26,
    marginTop: 8,
  },
  bubble: {
    maxWidth: '80%',
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 10,
    gap: 8,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.purple,
    borderBottomRightRadius: 6,
  },
  agentBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderBottomLeftRadius: 6,
  },
  userText: {
    color: colors.surface,
    fontSize: 16,
    lineHeight: 21,
  },
  agentText: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 21,
  },
  activityRow: {
    alignSelf: 'flex-start',
    maxWidth: '88%',
    marginLeft: 35,
    borderRadius: 14,
    backgroundColor: '#EEEAF4',
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 3,
  },
  activityTitle: {
    color: colors.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  activityMeta: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 15,
  },
  activityBody: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  warnPanel: {
    backgroundColor: '#FFF7E6',
    borderColor: '#F8D68D',
  },
  successPanel: {
    backgroundColor: '#EAFBF0',
    borderColor: '#BFECCF',
  },
  pendingPanel: {
    backgroundColor: colors.softPurple,
    borderColor: '#DDD2F4',
  },
  gatePanel: {
    alignSelf: 'stretch',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDD2F4',
    backgroundColor: colors.softPurple,
    padding: 14,
    gap: 10,
  },
  gateTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
  },
  gateBody: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  optionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#DDD2F4',
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  optionButtonActive: {
    backgroundColor: colors.purple,
    borderColor: colors.purple,
  },
  optionText: {
    color: colors.ink,
    fontWeight: '700',
  },
  optionTextActive: {
    color: colors.surface,
  },
  fieldBlock: {
    gap: 6,
  },
  composer: {
    backgroundColor: colors.soft,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
  },
  composerActions: {
    flexDirection: 'row',
    gap: 14,
  },
  composerActionButton: {
    minWidth: 78,
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  composerActionButtonText: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
  },
  attachmentActionTray: {
    alignSelf: 'flex-start',
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 6,
    ...softShadow,
  },
  attachmentActionButton: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.soft,
  },
  attachmentActionText: {
    color: colors.ink,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  composerInputShell: {
    flex: 1,
    minHeight: 48,
    maxHeight: 108,
    borderRadius: 24,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 14,
  },
  composerInputShellDisabled: {
    opacity: 0.72,
  },
  attachButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  attachPlus: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachPlusHorizontal: {
    position: 'absolute',
    width: 14,
    height: 2,
    borderRadius: 1,
    backgroundColor: colors.faint,
  },
  attachPlusVertical: {
    position: 'absolute',
    width: 2,
    height: 14,
    borderRadius: 1,
    backgroundColor: colors.faint,
  },
  composerInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 96,
    borderRadius: 0,
    color: colors.ink,
    paddingHorizontal: 0,
    paddingVertical: 11,
    fontSize: 16,
    lineHeight: 21,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: colors.purple,
  },
  sendButtonText: {
    color: colors.surface,
    fontWeight: '900',
    fontSize: 12,
  },
  sendArrowImage: {
    width: 16,
    height: 16,
  },
  sendStopIcon: {
    width: 13,
    height: 13,
    borderRadius: 3,
    backgroundColor: colors.surface,
  },
  attachmentStrip: {
    gap: 8,
  },
  attachmentPreview: {
    width: 118,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.soft,
    padding: 8,
    gap: 5,
  },
  attachmentImage: {
    width: '100%',
    height: 64,
    borderRadius: 10,
    backgroundColor: colors.line,
  },
  attachmentName: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  removeText: {
    color: colors.red,
    fontSize: 12,
    fontWeight: '800',
  },
  fileChip: {
    borderRadius: 10,
    backgroundColor: 'rgba(17,24,39,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  fileChipText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 15,
    padding: 18,
  },

  tabBar: {
    minHeight: 49,
    backgroundColor: colors.page,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    paddingHorizontal: 0,
    paddingTop: 4,
    paddingBottom: 0,
  },
  tabButton: {
    flex: 1,
    minHeight: 45,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tabButtonActive: {
    backgroundColor: colors.page,
  },
  tabButtonPressed: {
    opacity: 0.55,
  },
  tabText: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 13,
    fontWeight: '600',
  },
  tabTextActive: {
    color: colors.purple,
  },
  tabIconBox: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconImage: {
    width: 22,
    height: 22,
  },
});
