import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#17202A',
  muted: '#61717F',
  line: '#D7DEE6',
  page: '#F6F8FA',
  panel: '#FFFFFF',
  teal: '#146C6C',
  tealSoft: '#D9F0EE',
  blue: '#295C9E',
  amber: '#8A5B12',
  amberSoft: '#FFF0CF',
  red: '#A33A35',
  redSoft: '#FCE1DF',
  green: '#2D7A46',
  greenSoft: '#DFF3E5',
};

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.page,
  },
  header: {
    minHeight: 72,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
  },
  headerMeta: {
    alignItems: 'flex-end',
    gap: 6,
  },
  badge: {
    overflow: 'hidden',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '700',
  },
  badgeOk: {
    color: colors.green,
    backgroundColor: colors.greenSoft,
  },
  badgeWarn: {
    color: colors.amber,
    backgroundColor: colors.amberSoft,
  },
  addressText: {
    color: colors.muted,
    fontSize: 12,
  },
  errorBanner: {
    margin: 12,
    borderRadius: 8,
    padding: 10,
    color: colors.red,
    backgroundColor: colors.redSoft,
  },
  body: {
    flex: 1,
  },
  screenContent: {
    padding: 16,
    gap: 12,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 8,
  },
  panel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel,
    padding: 14,
    gap: 10,
  },
  label: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  valueText: {
    color: colors.ink,
    fontSize: 16,
  },
  input: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#FBFCFD',
    color: colors.ink,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  inputDisabled: {
    color: colors.muted,
    backgroundColor: '#EEF2F4',
  },
  multiline: {
    minHeight: 86,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  primaryButton: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: colors.teal,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  secondaryButton: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontWeight: '800',
  },
  dangerButton: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: colors.red,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  smallDangerButton: {
    minHeight: 34,
    borderRadius: 8,
    backgroundColor: colors.redSoft,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallDangerText: {
    color: colors.red,
    fontWeight: '800',
    fontSize: 12,
  },
  listRow: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  listMain: {
    flex: 1,
    gap: 3,
  },
  listTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  listMeta: {
    color: colors.muted,
    fontSize: 12,
  },
  chatLayout: {
    flex: 1,
  },
  modeBar: {
    minHeight: 54,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.panel,
  },
  modeButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 64,
    alignItems: 'center',
  },
  modeButtonActive: {
    backgroundColor: colors.tealSoft,
    borderColor: colors.teal,
  },
  modeText: {
    color: colors.muted,
    fontWeight: '800',
    fontSize: 12,
  },
  modeTextActive: {
    color: colors.teal,
  },
  modeCounter: {
    marginLeft: 'auto',
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    padding: 14,
    gap: 10,
  },
  bubble: {
    maxWidth: '88%',
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.blue,
  },
  agentBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
  },
  userText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 21,
  },
  agentText: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 21,
  },
  activityRow: {
    alignSelf: 'stretch',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.panel,
    padding: 11,
    gap: 4,
  },
  activityTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
  },
  activityMeta: {
    color: colors.muted,
    fontSize: 12,
  },
  activityBody: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  warnPanel: {
    backgroundColor: colors.amberSoft,
    borderColor: '#E0BF73',
  },
  successPanel: {
    backgroundColor: colors.greenSoft,
    borderColor: '#9DD3AE',
  },
  pendingPanel: {
    backgroundColor: '#EEF5FF',
    borderColor: '#B9CDE8',
  },
  gatePanel: {
    alignSelf: 'stretch',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#96BDBA',
    backgroundColor: colors.tealSoft,
    padding: 14,
    gap: 10,
  },
  gateTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
  },
  gateBody: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  optionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#96BDBA',
    backgroundColor: colors.panel,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  optionButtonActive: {
    backgroundColor: colors.teal,
    borderColor: colors.teal,
  },
  optionText: {
    color: colors.ink,
    fontWeight: '700',
  },
  optionTextActive: {
    color: '#FFFFFF',
  },
  fieldBlock: {
    gap: 6,
  },
  codeText: {
    color: colors.ink,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
    fontSize: 12,
    lineHeight: 18,
  },
  composer: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.panel,
    padding: 10,
    gap: 8,
  },
  composerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  composerInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#FBFCFD',
    color: colors.ink,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  sendButton: {
    minWidth: 68,
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#9AA8A8',
  },
  sendButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  attachmentStrip: {
    gap: 8,
  },
  attachmentPreview: {
    width: 118,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#FBFCFD',
    padding: 8,
    gap: 5,
  },
  attachmentImage: {
    width: '100%',
    height: 64,
    borderRadius: 6,
    backgroundColor: colors.line,
  },
  attachmentName: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  removeText: {
    color: colors.red,
    fontSize: 12,
    fontWeight: '800',
  },
  fileChip: {
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  fileChipText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 15,
    padding: 18,
  },
  tabBar: {
    minHeight: 68,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.panel,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  tabButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  tabButtonActive: {
    backgroundColor: colors.tealSoft,
  },
  tabText: {
    color: colors.muted,
    fontWeight: '800',
  },
  tabTextActive: {
    color: colors.teal,
  },
});
